// flow-typed signature: ae3fa0fd1bb51ec9706eeaf590229ea6
// flow-typed version: <<STUB>>/case-sensitive-paths-webpack-plugin_v1.1.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'case-sensitive-paths-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'case-sensitive-paths-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'case-sensitive-paths-webpack-plugin/demo/karma.conf' {
  declare module.exports: any;
}

declare module 'case-sensitive-paths-webpack-plugin/demo/servers/server' {
  declare module.exports: any;
}

declare module 'case-sensitive-paths-webpack-plugin/demo/src/AppRoot.component' {
  declare module.exports: any;
}

declare module 'case-sensitive-paths-webpack-plugin/demo/src/init' {
  declare module.exports: any;
}

declare module 'case-sensitive-paths-webpack-plugin/demo/src/utils/api' {
  declare module.exports: any;
}

declare module 'case-sensitive-paths-webpack-plugin/demo/tests.webpack' {
  declare module.exports: any;
}

declare module 'case-sensitive-paths-webpack-plugin/demo/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'case-sensitive-paths-webpack-plugin/demo/karma.conf.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin/demo/karma.conf'>;
}
declare module 'case-sensitive-paths-webpack-plugin/demo/servers/server.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin/demo/servers/server'>;
}
declare module 'case-sensitive-paths-webpack-plugin/demo/src/AppRoot.component.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin/demo/src/AppRoot.component'>;
}
declare module 'case-sensitive-paths-webpack-plugin/demo/src/init.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin/demo/src/init'>;
}
declare module 'case-sensitive-paths-webpack-plugin/demo/src/utils/api.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin/demo/src/utils/api'>;
}
declare module 'case-sensitive-paths-webpack-plugin/demo/tests.webpack.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin/demo/tests.webpack'>;
}
declare module 'case-sensitive-paths-webpack-plugin/demo/webpack.config.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin/demo/webpack.config'>;
}
declare module 'case-sensitive-paths-webpack-plugin/index' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin'>;
}
declare module 'case-sensitive-paths-webpack-plugin/index.js' {
  declare module.exports: $Exports<'case-sensitive-paths-webpack-plugin'>;
}
