// flow-typed signature: 303a3a944cb2f46a29f58664fe8574ca
// flow-typed version: <<STUB>>/dropbox_v^2.5.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dropbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dropbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dropbox/dist/dropbox-sdk' {
  declare module.exports: any;
}

declare module 'dropbox/dist/Dropbox-sdk.min' {
  declare module.exports: any;
}

declare module 'dropbox/dist/DropboxTeam-sdk.min' {
  declare module.exports: any;
}

declare module 'dropbox/src/download-request' {
  declare module.exports: any;
}

declare module 'dropbox/src/dropbox-base' {
  declare module.exports: any;
}

declare module 'dropbox/src/dropbox' {
  declare module.exports: any;
}

declare module 'dropbox/src/get-base-url' {
  declare module.exports: any;
}

declare module 'dropbox/src/index' {
  declare module.exports: any;
}

declare module 'dropbox/src/object-assign-polyfill' {
  declare module.exports: any;
}

declare module 'dropbox/src/request-constants' {
  declare module.exports: any;
}

declare module 'dropbox/src/routes-team' {
  declare module.exports: any;
}

declare module 'dropbox/src/routes' {
  declare module.exports: any;
}

declare module 'dropbox/src/rpc-request' {
  declare module.exports: any;
}

declare module 'dropbox/src/team/dropbox-team' {
  declare module.exports: any;
}

declare module 'dropbox/src/team/index' {
  declare module.exports: any;
}

declare module 'dropbox/src/types' {
  declare module.exports: any;
}

declare module 'dropbox/src/upload-request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dropbox/dist/dropbox-sdk.js' {
  declare module.exports: $Exports<'dropbox/dist/dropbox-sdk'>;
}
declare module 'dropbox/dist/Dropbox-sdk.min.js' {
  declare module.exports: $Exports<'dropbox/dist/Dropbox-sdk.min'>;
}
declare module 'dropbox/dist/DropboxTeam-sdk.min.js' {
  declare module.exports: $Exports<'dropbox/dist/DropboxTeam-sdk.min'>;
}
declare module 'dropbox/src/download-request.js' {
  declare module.exports: $Exports<'dropbox/src/download-request'>;
}
declare module 'dropbox/src/dropbox-base.js' {
  declare module.exports: $Exports<'dropbox/src/dropbox-base'>;
}
declare module 'dropbox/src/dropbox.js' {
  declare module.exports: $Exports<'dropbox/src/dropbox'>;
}
declare module 'dropbox/src/get-base-url.js' {
  declare module.exports: $Exports<'dropbox/src/get-base-url'>;
}
declare module 'dropbox/src/index.js' {
  declare module.exports: $Exports<'dropbox/src/index'>;
}
declare module 'dropbox/src/object-assign-polyfill.js' {
  declare module.exports: $Exports<'dropbox/src/object-assign-polyfill'>;
}
declare module 'dropbox/src/request-constants.js' {
  declare module.exports: $Exports<'dropbox/src/request-constants'>;
}
declare module 'dropbox/src/routes-team.js' {
  declare module.exports: $Exports<'dropbox/src/routes-team'>;
}
declare module 'dropbox/src/routes.js' {
  declare module.exports: $Exports<'dropbox/src/routes'>;
}
declare module 'dropbox/src/rpc-request.js' {
  declare module.exports: $Exports<'dropbox/src/rpc-request'>;
}
declare module 'dropbox/src/team/dropbox-team.js' {
  declare module.exports: $Exports<'dropbox/src/team/dropbox-team'>;
}
declare module 'dropbox/src/team/index.js' {
  declare module.exports: $Exports<'dropbox/src/team/index'>;
}
declare module 'dropbox/src/types.js' {
  declare module.exports: $Exports<'dropbox/src/types'>;
}
declare module 'dropbox/src/upload-request.js' {
  declare module.exports: $Exports<'dropbox/src/upload-request'>;
}
