// flow-typed signature: c0db7af8aae1fd9ed22dd827d391cc38
// flow-typed version: <<STUB>>/flow_vlatest/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow/flow' {
  declare module.exports: any;
}

declare module 'flow/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow/flow.js' {
  declare module.exports: $Exports<'flow/flow'>;
}
declare module 'flow/tests.js' {
  declare module.exports: $Exports<'flow/tests'>;
}
