// flow-typed signature: dd01b336c8c57723cca73024e39f52a4
// flow-typed version: <<STUB>>/loess_v^1.3.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loess'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loess' {
  declare type LoessData = {
    y: number[],
    x: number[],
    x2?: number[],
    w?: number[],
  };

  declare type LoessDegreeOption = 0 | 1 | 2 | 3 | 'constant' | 'linear' | 'quadratic';

  declare type LoessOptionsOptional = {
    span?: number,
    band?: number,
    degree?: LoessDegreeOption,
    normalize?: boolean,
    robust?: boolean,
    iterations?: number,
  };

  declare type LoessOptions = {
    span: number,
    band: number,
    degree: LoessDegreeOption,
    normalize: boolean,
    robust: boolean,
    iterations: number,
  };

  declare type LoessPredictionInput = {
    x: number[],
    x2?: number[],
  };

  declare class Loess {
    constructor(data: LoessData, options?: LoessOptionsOptional): Loess;
    data: LoessData;
    options: LoessOptions;
    y: number[];
    x: [number[], number[]];
    n: number;
    d: number;
    bandwidth: number;
    predict: (data?: LoessPredictionInput) => { fitted: number[], halfwidth: number[] };
    grid: (cuts: number[]) => { x_cut: number[], x_cut2: number[], x: number[], x2: number[] };
  }

  declare var exports: Class<Loess>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loess/dist/helpers' {
  declare module.exports: any;
}

declare module 'loess/dist/index' {
  declare module.exports: any;
}

declare module 'loess/dist/inputsValidation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loess/dist/helpers.js' {
  declare module.exports: $Exports<'loess/dist/helpers'>;
}
declare module 'loess/dist/index.js' {
  declare module.exports: $Exports<'loess/dist/index'>;
}
declare module 'loess/dist/inputsValidation.js' {
  declare module.exports: $Exports<'loess/dist/inputsValidation'>;
}
