// flow-typed signature: 19c0bf0f7ec073cff0d75b6b4a272a3f
// flow-typed version: <<STUB>>/radium-normalize_v^2.0.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'radium-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'radium-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'radium-normalize/normalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'radium-normalize/normalize.js' {
  declare module.exports: $Exports<'radium-normalize/normalize'>;
}
